# Generated by Django 4.1.3 on 2022-11-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fungsi_Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fungsi_obat', models.CharField(max_length=20)),
                ('keterangan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_brg', models.CharField(max_length=10)),
                ('nama_obat', models.CharField(max_length=20)),
                ('stock', models.IntegerField(max_length=4)),
                ('harga', models.BigIntegerField(max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('jenis_obat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Obat.fungsi_obat')),
            ],
        ),
    ]
