# Generated by Django 4.1.3 on 2022-11-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='harga',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='obat',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
