# Generated by Django 4.1.2 on 2022-11-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obat', '0002_alter_obat_harga_alter_obat_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='obat',
            name='kadarluarsa',
            field=models.DateField(null=True),
        ),
    ]
