# Generated by Django 4.1.2 on 2022-11-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obat', '0003_obat_kadarluarsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='obat',
            name='supplier',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
