# Generated by Django 4.1.2 on 2022-11-17 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Karyawan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='birth_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='birth_place',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
