# Generated by Django 4.1.2 on 2022-11-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karyawan', '0002_karyawan_birth_day_karyawan_birth_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
